# Change these first
owner: atnauman # Your GitHub organization or username, where this repository lives
repo: service-status # The name of this repository

sites:
  - name: Mellite Service 
    url:  https://mellite.bihealth.org
  - name: Geo App service
    url:  https://geoapp.bihealth.org

 # - name: Keycloak Dataloft-Catalogue
 #   url: https://auth.gxfs-catalogue.dataloft-ionos.de/partici
#  - name: de.NBI Cloud Berlin
#    url: https://denbi-cloud.bihealth.org
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /service-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Service Status** is monitor and status page for data management group services."
  introMessage: This status page shows **real-time** data from the listed services. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
